var diamondsData = [
  {
    "Qty": 1,
    "Lot ID": "790185947",
    "Size": "0.90-0.99",
    "Carat": 0.9,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "E",
    "Clarity": "VVS2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -44,
    "Per Carat Rate": 3864,
    "Final Amount": 3477.6,
    "Key To Symbol": "Cloud, Indented Natural, Cavity, Natural",
    "Lab Comment": "Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "490361405",
    "Size": "0.90-0.99",
    "Carat": 0.9,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "G",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -41,
    "Per Carat Rate": 3776,
    "Final Amount": 3398.4,
    "Key To Symbol": "Pinpoint",
  },
  {
    "Qty": 1,
    "Lot ID": "790367521",
    "Size": "1.00-1.49",
    "Carat": 1,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "VVS2",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "G",
    "Fluorescence": "MED",
    "Discount": -58.98,
    "Per Carat Rate": 3445.68,
    "Final Amount": 3445.68,
    "Key To Symbol": "Cloud, Pinpoint, Indented Natural",
    "Lab Comment":
        "Additional pinpoints are not shown. Surface graining is not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "490361912",
    "Size": "1.00-1.49",
    "Carat": 1,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VVS2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -41,
    "Per Carat Rate": 3245,
    "Final Amount": 3245,
    "Key To Symbol": "Needle, Pinpoint, Indented Natural, Natural",
    "Lab Comment": "Additional pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "790386188",
    "Size": "1.00-1.49",
    "Carat": 1.01,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "VS1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -49.12,
    "Per Carat Rate": 3663.36,
    "Final Amount": 3699.9936,
    "Key To Symbol": "Crystal, Needle",
    "Lab Comment": "Pinpoints are not shown. Clouds are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "21287670",
    "Size": "1.00-1.49",
    "Carat": 1.01,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "G",
    "Clarity": "I1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -48.42,
    "Per Carat Rate": 1598.98,
    "Final Amount": 1614.9698,
  },
  {
    "Qty": 1,
    "Lot ID": "790146218",
    "Size": "1.00-1.49",
    "Carat": 1.2,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "G",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -41.48,
    "Per Carat Rate": 3628.24,
    "Final Amount": 4353.888,
    "Key To Symbol": "Crystal, Cloud, Needle",
    "Lab Comment": "Additional clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "900066231",
    "Size": "1.00-1.49",
    "Carat": 1.44,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "VS2",
    "Cut": "G",
    "Polish": "G",
    "Symmetry": "G",
    "Fluorescence": "MED",
    "Discount": -94,
    "Per Carat Rate": 402,
    "Final Amount": 578.88,
  },
  {
    "Qty": 1,
    "Lot ID": "900061985",
    "Size": "1.00-1.49",
    "Carat": 1.46,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VS2",
    "Cut": "G",
    "Polish": "G",
    "Symmetry": "G",
    "Fluorescence": "MED",
    "Discount": -94,
    "Per Carat Rate": 324,
    "Final Amount": 473.04,
  },
  {
    "Qty": 1,
    "Lot ID": "490345395",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "FL",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -18,
    "Per Carat Rate": 2296,
    "Final Amount": 688.8,
  },
  {
    "Qty": 1,
    "Lot ID": "490370762",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -35,
    "Per Carat Rate": 1560,
    "Final Amount": 468,
    "Key To Symbol": "Pinpoint",
  },
  {
    "Qty": 1,
    "Lot ID": "1712094",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "VG",
    "Polish": "VG",
    "Symmetry": "EX",
    "Fluorescence": "MED",
    "Discount": -52.5,
    "Per Carat Rate": 1140,
    "Final Amount": 342,
    "Key To Symbol": "Cavity, Feather, Indented Natural",
  },
  {
    "Qty": 1,
    "Lot ID": "900057394",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -38,
    "Per Carat Rate": 1488,
    "Final Amount": 446.4,
    "Key To Symbol": "Pinpoint, Feather",
  },
  {
    "Qty": 1,
    "Lot ID": "900055819",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -38,
    "Per Carat Rate": 1488,
    "Final Amount": 446.4,
    "Key To Symbol": "Pinpoint",
  },
  {
    "Qty": 1,
    "Lot ID": "1706382",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "VG",
    "Polish": "VG",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -48,
    "Per Carat Rate": 1248,
    "Final Amount": 374.4,
    "Key To Symbol": "Pinpoint, Feather, Chip",
  },
  {
    "Qty": 1,
    "Lot ID": "290135752",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -48.5,
    "Per Carat Rate": 1236,
    "Final Amount": 370.8,
    "Key To Symbol": "Pinpoint, Feather",
  },
  {
    "Qty": 1,
    "Lot ID": "490250218",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -47.5,
    "Per Carat Rate": 1260,
    "Final Amount": 378,
    "Key To Symbol": "Pinpoint, Feather",
  },
  {
    "Qty": 1,
    "Lot ID": "490167040",
    "Size": "0.30-0.39",
    "Carat": 0.3,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -47.5,
    "Per Carat Rate": 1260,
    "Final Amount": 378,
    "Key To Symbol": "Pinpoint, Feather",
  },
  {
    "Qty": 1,
    "Lot ID": "900066356",
    "Size": "0.18-0.22",
    "Carat": 0.18,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -37.67,
    "Per Carat Rate": 785.36,
    "Final Amount": 141.3648,
  },
  {
    "Qty": 1,
    "Lot ID": "900064899",
    "Size": "0.18-0.22",
    "Carat": 0.18,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -37.67,
    "Per Carat Rate": 785.36,
    "Final Amount": 141.3648,
  },
  {
    "Qty": 1,
    "Lot ID": "900067131",
    "Size": "0.23-0.29",
    "Carat": 0.23,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "SI2",
    "Cut": "VG",
    "Polish": "VG",
    "Symmetry": "VG",
    "Fluorescence": "MED",
    "Discount": -37.28,
    "Per Carat Rate": 683.65,
    "Final Amount": 157.2395,
  },
  {
    "Qty": 1,
    "Lot ID": "900066716",
    "Size": "0.23-0.29",
    "Carat": 0.23,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "E",
    "Clarity": "SI2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -37.28,
    "Per Carat Rate": 683.65,
    "Final Amount": 157.2395,
  },
  {
    "Qty": 1,
    "Lot ID": "900062564",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -41,
    "Per Carat Rate": 32450,
    "Final Amount": 97674.5,
    "Lab Comment": "Minor details of polish are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "900065188",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -39,
    "Per Carat Rate": 28060,
    "Final Amount": 84460.6,
    "Key To Symbol": "Pinpoint",
    "Lab Comment": "Additional pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "290187276",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -43,
    "Per Carat Rate": 26220,
    "Final Amount": 78922.2,
    "Key To Symbol": "Pinpoint, Needle",
  },
  {
    "Qty": 1,
    "Lot ID": "900061478",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "VVS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -38,
    "Per Carat Rate": 28520,
    "Final Amount": 85845.2,
    "Key To Symbol": "Feather",
  },
  {
    "Qty": 1,
    "Lot ID": "21214039",
    "Size": "2.00-2.99",
    "Carat": 2,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -38,
    "Per Carat Rate": 7750,
    "Final Amount": 15500,
    "Key To Symbol": "Cloud, Crystal, Feather, Needle, Natural",
    "Lab Comment": "Additional clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "21269689",
    "Size": "2.00-2.99",
    "Carat": 2,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -34,
    "Per Carat Rate": 8250,
    "Final Amount": 16500,
    "Key To Symbol": "Crystal, Cloud, Indented Natural, Natural",
    "Lab Comment":
        "Additional clouds, pinpoints and surface graining are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "112209404",
    "Size": "2.00-2.99",
    "Carat": 2,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -39,
    "Per Carat Rate": 7625,
    "Final Amount": 15250,
    "Key To Symbol": "Crystal, Indented Natural, Needle, Natural",
    "Lab Comment": "Clouds, pinpoints and surface graining are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "900064418",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "SI1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "MED",
    "Discount": -51,
    "Per Carat Rate": 6027,
    "Final Amount": 12114.27,
    "Key To Symbol":
        "Crystal, Twinning Wisp, Feather, Needle, Indented Natural",
    "Lab Comment":
        "Additional twinning wisps, pinpoints and surface graining are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "1709323",
    "Size": "2.00-2.99",
    "Carat": 2.54,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "SI2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -48,
    "Per Carat Rate": 5096,
    "Final Amount": 12943.84,
  },
  {
    "Qty": 1,
    "Lot ID": "21126224",
    "Size": "3.00-3.99",
    "Carat": 3.02,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "I1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "MED",
    "Discount": -56.98,
    "Per Carat Rate": 3527.64,
    "Final Amount": 10653.4728,
  },
  {
    "Qty": 1,
    "Lot ID": "21155574",
    "Size": "3.00-3.99",
    "Carat": 3.05,
    "Lab": "In-House",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "I1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -56.98,
    "Per Carat Rate": 3527.64,
    "Final Amount": 10759.302,
  },
  {
    "Qty": 1,
    "Lot ID": "911036108",
    "Size": "2.00-2.99",
    "Carat": 2,
    "Lab": "GIA",
    "Shape": "CU",
    "Color": "G",
    "Clarity": "VS1",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -47,
    "Per Carat Rate": 7420,
    "Final Amount": 14840,
    "Lab Comment": "Clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "290053887",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "CU",
    "Color": "E",
    "Clarity": "VVS1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -52.86,
    "Per Carat Rate": 8720.9,
    "Final Amount": 17529.009,
  },
  {
    "Qty": 1,
    "Lot ID": "900691763",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "CU",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -60.59,
    "Per Carat Rate": 5123.3,
    "Final Amount": 10297.833,
  },
  {
    "Qty": 1,
    "Lot ID": "900691769",
    "Size": "3.00-3.99",
    "Carat": 3,
    "Lab": "GIA",
    "Shape": "CU",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -56,
    "Per Carat Rate": 9020,
    "Final Amount": 27060,
  },
  {
    "Qty": 1,
    "Lot ID": "911036111",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "CU",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -40,
    "Per Carat Rate": 12300,
    "Final Amount": 37023,
  },
  {
    "Qty": 1,
    "Lot ID": "290035976",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "CU",
    "Color": "H",
    "Clarity": "VS1",
    "Polish": "VG",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -58,
    "Per Carat Rate": 8190,
    "Final Amount": 24651.9,
  },
  {
    "Qty": 1,
    "Lot ID": "911036101",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -52,
    "Per Carat Rate": 12542.4,
    "Final Amount": 25210.224,
    "Lab Comment": "Additional clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "20289242",
    "Size": "2.00-2.99",
    "Carat": 2.07,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "D",
    "Clarity": "VVS1",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -55.05,
    "Per Carat Rate": 8990,
    "Final Amount": 18609.3,
    "Lab Comment":
        "Internal graining is not shown. Surface graining is not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "290114652",
    "Size": "2.00-2.99",
    "Carat": 2.82,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -35,
    "Per Carat Rate": 8450,
    "Final Amount": 23829,
  },
  {
    "Qty": 1,
    "Lot ID": "911026173",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "F",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "VST",
    "Discount": -65,
    "Per Carat Rate": 7875,
    "Final Amount": 23703.75,
  },
  {
    "Qty": 1,
    "Lot ID": "911035850",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "F",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -45,
    "Per Carat Rate": 12375,
    "Final Amount": 37248.75,
  },
  {
    "Qty": 1,
    "Lot ID": "290157034",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "F",
    "Clarity": "SI1",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -46,
    "Per Carat Rate": 10530,
    "Final Amount": 31695.3,
  },
  {
    "Qty": 1,
    "Lot ID": "911024106",
    "Size": "3.00-3.99",
    "Carat": 3.02,
    "Lab": "GIA",
    "Shape": "EM",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -50,
    "Per Carat Rate": 10250,
    "Final Amount": 30955,
  },
  {
    "Qty": 1,
    "Lot ID": "7513951",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "MQ",
    "Color": "D",
    "Clarity": "VVS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -35.41,
    "Per Carat Rate": 11949.15,
    "Final Amount": 24017.7915,
  },
  {
    "Qty": 1,
    "Lot ID": "900045732",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "VG",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -41,
    "Per Carat Rate": 7670,
    "Final Amount": 15416.7,
  },
  {
    "Qty": 1,
    "Lot ID": "900779752",
    "Size": "2.00-2.99",
    "Carat": 2.68,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "E",
    "Clarity": "VS1",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -32,
    "Per Carat Rate": 10880,
    "Final Amount": 29158.4,
  },
  {
    "Qty": 1,
    "Lot ID": "900579422",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "G",
    "Clarity": "SI1",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -40,
    "Per Carat Rate": 10800,
    "Final Amount": 32508,
  },
  {
    "Qty": 1,
    "Lot ID": "901000037",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "H",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -41,
    "Per Carat Rate": 10620,
    "Final Amount": 31966.2,
  },
  {
    "Qty": 1,
    "Lot ID": "290186284",
    "Size": "3.00-3.99",
    "Carat": 3.02,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "F",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -40,
    "Per Carat Rate": 9300,
    "Final Amount": 28086,
  },
  {
    "Qty": 1,
    "Lot ID": "290115870",
    "Size": "2.00-2.99",
    "Carat": 2.5,
    "Lab": "GIA",
    "Shape": "PR",
    "Color": "E",
    "Clarity": "VS2",
    "Polish": "VG",
    "Symmetry": "G",
    "Fluorescence": "NON",
    "Discount": -51,
    "Per Carat Rate": 7350,
    "Final Amount": 18375,
    "Lab Comment": "Clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "900723209",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "GIA",
    "Shape": "PS",
    "Color": "F",
    "Clarity": "VVS2",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -37,
    "Per Carat Rate": 10080,
    "Final Amount": 20260.8,
  },
  {
    "Qty": 1,
    "Lot ID": "900622172",
    "Size": "0.50-0.69",
    "Carat": 0.5,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "E",
    "Clarity": "VS1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -51.3,
    "Per Carat Rate": 1217.5,
    "Final Amount": 608.75,
  },
  {
    "Qty": 1,
    "Lot ID": "900622170",
    "Size": "0.50-0.69",
    "Carat": 0.5,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "E",
    "Clarity": "VS1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -48.07,
    "Per Carat Rate": 1298.25,
    "Final Amount": 649.125,
  },
  {
    "Qty": 1,
    "Lot ID": "900622171",
    "Size": "0.50-0.69",
    "Carat": 0.5,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "E",
    "Clarity": "SI1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -56,
    "Per Carat Rate": 924,
    "Final Amount": 462,
  },
  {
    "Qty": 1,
    "Lot ID": "900691721",
    "Size": "0.50-0.69",
    "Carat": 0.5,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "G",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -48.45,
    "Per Carat Rate": 1082.55,
    "Final Amount": 541.275,
  },
  {
    "Qty": 1,
    "Lot ID": "900622186",
    "Size": "0.50-0.69",
    "Carat": 0.59,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "E",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -51,
    "Per Carat Rate": 1127,
    "Final Amount": 664.93,
  },
  {
    "Qty": 1,
    "Lot ID": "900691730",
    "Size": "0.70-0.89",
    "Carat": 0.7,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "F",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -51.58,
    "Per Carat Rate": 1452.6,
    "Final Amount": 1016.82,
  },
  {
    "Qty": 1,
    "Lot ID": "900691734",
    "Size": "0.70-0.89",
    "Carat": 0.7,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "G",
    "Clarity": "VS1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -46.92,
    "Per Carat Rate": 1645.48,
    "Final Amount": 1151.836,
  },
  {
    "Qty": 1,
    "Lot ID": "900691737",
    "Size": "0.70-0.89",
    "Carat": 0.7,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "G",
    "Clarity": "SI1",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "FNT",
    "Discount": -48.77,
    "Per Carat Rate": 1127.06,
    "Final Amount": 788.942,
  },
  {
    "Qty": 1,
    "Lot ID": "900622198",
    "Size": "0.70-0.89",
    "Carat": 0.7,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "I",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -44.42,
    "Per Carat Rate": 1222.76,
    "Final Amount": 855.932,
  },
  {
    "Qty": 1,
    "Lot ID": "900478081",
    "Size": "0.70-0.89",
    "Carat": 0.8,
    "Lab": "GIA",
    "Shape": "OV",
    "Color": "J",
    "Clarity": "SI1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -37.41,
    "Per Carat Rate": 1064.03,
    "Final Amount": 851.224,
  },
  {
    "Qty": 1,
    "Lot ID": "490070471",
    "Size": "1.00-1.49",
    "Carat": 1.01,
    "Lab": "GIA",
    "Shape": "PS",
    "Color": "G",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -46.55,
    "Per Carat Rate": 1763.85,
    "Final Amount": 1781.4885,
    "Lab Comment": "Clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "290168948",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "GIA",
    "Shape": "RAD",
    "Color": "G",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -56,
    "Per Carat Rate": 6380,
    "Final Amount": 19203.8,
  },
  {
    "Qty": 1,
    "Lot ID": "790339140",
    "Size": "1.50-1.99",
    "Carat": 1.7,
    "Lab": "GIA",
    "Shape": "BR",
    "Color": "K",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -48,
    "Per Carat Rate": 2444,
    "Final Amount": 4154.8,
  },
  {
    "Qty": 1,
    "Lot ID": "790377407",
    "Size": "0.90-0.99",
    "Carat": 0.92,
    "Lab": "GIA",
    "Shape": "PS",
    "Color": "D",
    "Clarity": "VS2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -40.77,
    "Per Carat Rate": 2606.12,
    "Final Amount": 2397.6304,
    "Lab Comment": "Clouds, pinpoints and surface graining are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "7482482",
    "Size": "1.00-1.49",
    "Carat": 1.01,
    "Lab": "GIA",
    "Shape": "PS",
    "Color": "I",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -52.5,
    "Per Carat Rate": 1330,
    "Final Amount": 1343.3,
    "Lab Comment": "Clouds, pinpoints and surface graining are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "490017318",
    "Size": "5.00-5.99",
    "Carat": 5.01,
    "Lab": "GIA",
    "Shape": "RAD",
    "Color": "H",
    "Clarity": "VS1",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "FNT",
    "Discount": -50.71,
    "Per Carat Rate": 16512.15,
    "Final Amount": 82725.8715,
  },
  {
    "Qty": 1,
    "Lot ID": "17463537",
    "Size": "3.00-3.99",
    "Carat": 3.19,
    "Lab": "GIA",
    "Shape": "PS",
    "Color": "D",
    "Clarity": "SI1",
    "Polish": "VG",
    "Symmetry": "G",
    "Fluorescence": "FNT",
    "Discount": -71,
    "Per Carat Rate": 6670,
    "Final Amount": 21277.3,
    "Lab Comment":
        "Additional twinning, pinpoints, surface graining and additional extra facets are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "21230187",
    "Size": "1.00-1.49",
    "Carat": 1,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "SI2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -54,
    "Per Carat Rate": 1840,
    "Final Amount": 1840,
  },
  {
    "Qty": 1,
    "Lot ID": "21235183",
    "Size": "1.00-1.49",
    "Carat": 1,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "SI2",
    "Cut": "G",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -64,
    "Per Carat Rate": 1512,
    "Final Amount": 1512,
  },
  {
    "Qty": 1,
    "Lot ID": "7522163",
    "Size": "1.00-1.49",
    "Carat": 1,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "M",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -50.09,
    "Per Carat Rate": 1147.93,
    "Final Amount": 1147.93,
  },
  {
    "Qty": 1,
    "Lot ID": "21240435",
    "Size": "1.00-1.49",
    "Carat": 1.01,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "F",
    "Clarity": "SI2",
    "Cut": "VG",
    "Polish": "VG",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -59,
    "Per Carat Rate": 1722,
    "Final Amount": 1739.22,
  },
  {
    "Qty": 1,
    "Lot ID": "1691633",
    "Size": "1.00-1.49",
    "Carat": 1.2,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -49.84,
    "Per Carat Rate": 3059.76,
    "Final Amount": 3671.712,
  },
  {
    "Qty": 1,
    "Lot ID": "490171786",
    "Size": "1.00-1.49",
    "Carat": 1.2,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -49.84,
    "Per Carat Rate": 3059.76,
    "Final Amount": 3671.712,
    "Lab Comment": "Minor details of polish are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "1700572",
    "Size": "1.00-1.49",
    "Carat": 1.21,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -50.89,
    "Per Carat Rate": 2995.71,
    "Final Amount": 3624.8091,
  },
  {
    "Qty": 1,
    "Lot ID": "1672088",
    "Size": "1.00-1.49",
    "Carat": 1.25,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -49.84,
    "Per Carat Rate": 3059.76,
    "Final Amount": 3824.7,
  },
  {
    "Qty": 1,
    "Lot ID": "490142601",
    "Size": "1.00-1.49",
    "Carat": 1.31,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "G",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -52,
    "Per Carat Rate": 3936,
    "Final Amount": 5156.16,
    "Lab Comment": "minor graining",
  },
  {
    "Qty": 1,
    "Lot ID": "490297520",
    "Size": "1.50-1.99",
    "Carat": 1.5,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "M",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -53,
    "Per Carat Rate": 1692,
    "Final Amount": 2538,
  },
  {
    "Qty": 1,
    "Lot ID": "490267195",
    "Size": "1.50-1.99",
    "Carat": 1.7,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "L",
    "Clarity": "VS1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "SLT",
    "Discount": -54,
    "Per Carat Rate": 1840,
    "Final Amount": 3128,
    "Key To Symbol": "Cloud, Needle, Indented Natural, Natural",
    "Lab Comment": "Additional clouds are not shown. Pinpoints are not shown.",
  },
  {
    "Qty": 1,
    "Lot ID": "290148072",
    "Size": "1.50-1.99",
    "Carat": 1.8,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "L",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "STG",
    "Discount": -54,
    "Per Carat Rate": 1840,
    "Final Amount": 3312,
  },
  {
    "Qty": 1,
    "Lot ID": "1673222",
    "Size": "1.50-1.99",
    "Carat": 1.8,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "M",
    "Clarity": "VS2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -47,
    "Per Carat Rate": 1802,
    "Final Amount": 3243.6,
  },
  {
    "Qty": 1,
    "Lot ID": "490296096",
    "Size": "1.50-1.99",
    "Carat": 1.8,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "M",
    "Clarity": "VS2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -48,
    "Per Carat Rate": 1768,
    "Final Amount": 3182.4,
  },
  {
    "Qty": 1,
    "Lot ID": "1682094",
    "Size": "2.00-2.99",
    "Carat": 2.01,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "K",
    "Clarity": "SI1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -56,
    "Per Carat Rate": 2508,
    "Final Amount": 5041.08,
  },
  {
    "Qty": 1,
    "Lot ID": "21245651",
    "Size": "2.00-2.99",
    "Carat": 2.03,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "K",
    "Clarity": "SI1",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -58,
    "Per Carat Rate": 2394,
    "Final Amount": 4859.82,
  },
  {
    "Qty": 1,
    "Lot ID": "7537173",
    "Size": "2.00-2.99",
    "Carat": 2.8,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "IF",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -36,
    "Per Carat Rate": 10560,
    "Final Amount": 29568,
  },
  {
    "Qty": 1,
    "Lot ID": "1709599",
    "Size": "3.00-3.99",
    "Carat": 3,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "G",
    "Clarity": "SI2",
    "Cut": "G",
    "Polish": "VG",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -58.4,
    "Per Carat Rate": 3203.2,
    "Final Amount": 9609.6,
  },
  {
    "Qty": 1,
    "Lot ID": "445298427",
    "Size": "3.00-3.99",
    "Carat": 3,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VVS2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -58,
    "Per Carat Rate": 9450,
    "Final Amount": 28350,
  },
  {
    "Qty": 1,
    "Lot ID": "1709329",
    "Size": "3.00-3.99",
    "Carat": 3.01,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "G",
    "Clarity": "SI2",
    "Cut": "VG",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -58,
    "Per Carat Rate": 6510,
    "Final Amount": 19595.1,
  },
  {
    "Qty": 1,
    "Lot ID": "1706899",
    "Size": "3.00-3.99",
    "Carat": 3.03,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "J",
    "Clarity": "VVS2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -54,
    "Per Carat Rate": 6900,
    "Final Amount": 20907,
  },
  {
    "Qty": 1,
    "Lot ID": "1696732",
    "Size": "3.00-3.99",
    "Carat": 3.5,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "J",
    "Clarity": "SI2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -46,
    "Per Carat Rate": 5940,
    "Final Amount": 20790,
  },
  {
    "Qty": 1,
    "Lot ID": "900058991",
    "Size": "3.00-3.99",
    "Carat": 3.52,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "D",
    "Clarity": "SI2",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "SLT",
    "Discount": -51,
    "Per Carat Rate": 9800,
    "Final Amount": 34496,
  },
  {
    "Qty": 1,
    "Lot ID": "1709601",
    "Size": "3.00-3.99",
    "Carat": 3.52,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "H",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -51,
    "Per Carat Rate": 10045,
    "Final Amount": 35358.4,
  },
  {
    "Qty": 1,
    "Lot ID": "900054495",
    "Size": "3.00-3.99",
    "Carat": 3.8,
    "Lab": "HRD",
    "Shape": "BR",
    "Color": "K",
    "Clarity": "VS1",
    "Cut": "EX",
    "Polish": "EX",
    "Symmetry": "EX",
    "Fluorescence": "NON",
    "Discount": -46,
    "Per Carat Rate": 6480,
    "Final Amount": 24624,
  },
  {
    "Qty": 1,
    "Lot ID": "900057220",
    "Size": "3.00-3.99",
    "Carat": 3.02,
    "Lab": "HRD",
    "Shape": "HS",
    "Color": "H",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "SLT",
    "Discount": -61,
    "Per Carat Rate": 5265,
    "Final Amount": 15900.3,
  },
  {
    "Qty": 1,
    "Lot ID": "1706907",
    "Size": "3.00-3.99",
    "Carat": 3,
    "Lab": "HRD",
    "Shape": "OV",
    "Color": "F",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "SLT",
    "Discount": -56,
    "Per Carat Rate": 6820,
    "Final Amount": 20460,
  },
  {
    "Qty": 1,
    "Lot ID": "445568009",
    "Size": "0.90-0.99",
    "Carat": 0.9,
    "Lab": "HRD",
    "Shape": "PS",
    "Color": "F",
    "Clarity": "SI2",
    "Polish": "EX",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -52,
    "Per Carat Rate": 1392,
    "Final Amount": 1252.8,
  },
  {
    "Qty": 1,
    "Lot ID": "445376109",
    "Size": "1.00-1.49",
    "Carat": 1,
    "Lab": "HRD",
    "Shape": "PS",
    "Color": "F",
    "Clarity": "SI2",
    "Polish": "VG",
    "Symmetry": "VG",
    "Fluorescence": "NON",
    "Discount": -58,
    "Per Carat Rate": 1470,
    "Final Amount": 1470,
  },
  {
    "Qty": 100,
    "Lot ID": 100,
    "Carat": 178.3,
    "Discount": -48.8412,
    "Per Carat Rate": 5672.2978,
    "Final Amount": 1446192.1698,
  },
];
